<a href="https://colab.research.google.com/github/Rojakarilakshmiprasanna/11239A077_DAA_LAB/blob/main/11239A077_EXP6B_SP_USING_WAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

def floyd_warshall(graph):
    num_vertices = len(graph)
    distance = np.full((num_vertices, num_vertices), np.inf)

    # Step 1 & 2: Initialize distance matrix
    for i in range(num_vertices):
        distance[i][i] = 0
        for j in range(num_vertices):
            if graph[i][j] != 0:
                distance[i][j] = graph[i][j]

    # Step 3 & 4: Floyd-Warshall algorithm
    for k in range(num_vertices):
        for i in range(num_vertices):
            for j in range(num_vertices):
                if distance[i][j] > distance[i][k] + distance[k][j]:
                    distance[i][j] = distance[i][k] + distance[k][j]

    # Step 5: Return distance matrix
    return distance

# Step 6: Define the graph
graph = [
    [0, 1, np.inf],
    [1, 0, 2],
    [np.inf, 2, 0]
]

# Call the function
shortest_paths = floyd_warshall(graph)

# Output the result
print("Shortest path distance matrix:")
print(shortest_paths)

Shortest path distance matrix:
[[0. 1. 3.]
 [1. 0. 2.]
 [3. 2. 0.]]
